# Generated by Django 4.2 on 2026-03-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('tea', 'Morning Tea'), ('lunch', 'Lunch'), ('evening', 'Evening'), ('breakfast', 'Breakfast'), ('dinner', 'Dinner')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_date', models.DateField()),
                ('max_servings', models.IntegerField(default=100)),
                ('current_orders', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['available_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('tea', 'Morning Tea'), ('lunch', 'Lunch'), ('evening', 'Evening')], default='lunch', max_length=20)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('served', 'Served'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='meals.meal')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='restaurants.restaurant')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_orders',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'meal_type', 'order_date')},
            },
        ),
    ]
